# Generated by Django 5.2.1 on 2025-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_brand_product_color_product_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
