# Generated by Django 5.2.1 on 2025-07-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_customer_old_cart_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
