# Generated by Django 5.2.1 on 2025-07-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_profile_old_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
